name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk python3-pip python3-setuptools git libncurses5

    - name: Initialize buildozer.spec
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi

    - name: Set permissions
      run: chmod +x ./main.py

    - name: Build APK
      run: |
        buildozer -v android debug

    - name: Upload APK
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: kivy-apk
        path: bin/*.apk
