name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Você pode mudar para a versão que está usando

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        sudo apt-get install -y python3-pip
        pip install --upgrade pip
        pip install buildozer
        sudo apt-get install -y python3-venv
        sudo apt-get install -y libssl-dev
        sudo apt-get install -y libsdl2-dev
        sudo apt-get install -y libjpeg-dev
        sudo apt-get install -y libfreetype6-dev

    - name: Set up Buildozer
      run: |
        mkdir -p ~/.buildozer
        buildozer init  # Se você já tiver o arquivo buildozer.spec, você pode pular essa linha

    - name: Build APK with Buildozer
      run: |
        cd path/to/your/project  # Substitua pelo caminho correto do seu projeto
        buildozer -v android debug  # Você pode alterar a opção para release, se necessário
